### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by tyrsson** [divix1988/laminas_examples#10]
When using the helper with a Captcha element in a form there is an undefined index reported on line 138 due to $type being null. Adding !empty($type) appears to have fixed it for me. If I run into any problems I will updated the issue. Check is on line 94.

**Comment by divix1988** [comment]
Thanks for letting me know, I have patched the affected line with `isset()` instead. Commit: `2251acb530f20146231af7246595c8905c691773`
