### ISSUE TITLE
An error occurred when save data

### ISSUE THREAD

**Issue by thanh858036** [divix1988/laminas_examples#3]
Argument 1 passed to Application\Model\AbstractTable::saveRow() must be an instance of Application\Model\Rowset\AbstractModel, instance of Application\Model\Rowset\User given, called in Application\src\Model\UsersTable.php on line 23

**Comment by divix1988** [comment]
Which chapter is that?

You need to add  
`class User extends AbstractModel`
in order to fix the issue.

**Comment by thanh858036** [comment]
from chapter 6 error occurred when save data
i already add
`class User extends AbstractModel implements InputFilterAwareInterface`
i think
class UsersTable
`public function save(User $userModel)` a User model
class AbstractTable
`public function saveRow(AbstractModel $userModel, $data = null)` a AbstractModel model

**Comment by divix1988** [comment]
Fixed the issue by added missing line: https://github.com/divix1988/laminas_examples/commit/02c31f2275c30164c258d8f83aaf084d91b84878

Since the `User` rowset model wasn't printed in the book, there is no need to update the book though.

@thanh858036  Thanks for catching up a bug! 👍
