### ISSUE TITLE
Problem with route

### ISSUE THREAD

**Issue by thanh858036** [divix1988/laminas_examples#5]
In Chapter 11
`$userForm->setAttribute('action', $this->url('users', ['action' => 'add']));` in `add.phtml`
Form Action url `\comics_list` that indexAction class `UsersController` not to addAction

**Comment by thanh858036** [comment]
`$userForm->setAttribute('action', $this->url('users', ['action' => 'add']));` in `add.phtml` should be
`$userForm->setAttribute('action', $this->url('users/add', ['action' => 'add']));`

**Comment by divix1988** [comment]
Not really, the `$this->url('users', ['action' => 'add'])` should work in this exmaple. You pass the route options into second argument of `url()` method. 

Where did you get `\comics_list` ? `UsersController` don't have that in: https://github.com/divix1988/laminas_examples/blob/master/Chapter%2011/module/Application/src/Controller/UsersController.php

Check if you have the route correctly setup in `module.config.php`

```
            'users' => [
                'type' => Segment::class,
                'options' => [
                    'route' => '/users[/:action[/:id]]',
                    'defaults' => [
                        'controller' => Controller\UsersController::class,
                        'action' => 'index',
                    ],
                ],
            ],
```

**Comment by thanh858036** [comment]
how to route users can use paginator. I copy from route comics can use paginator but can use edit and delete action

**Comment by divix1988** [comment]
You can use something like that to include pagination into Users  example.

```
'users' => [
    'type' => Segment::class,
    'options' => [
        'route' => '/users',
        'defaults' => [
            'controller' => Controller\UsersController::class,
            'action' => 'index',
        ],
    ],
    'may_terminate' => true,
    'child_routes' => [
        'add' => [
            'type' => 'literal',
            'options' => [
                'route' => '/add',
                'defaults' => [
                    'controller' => Controller\UsersController::class,
                    'action' => 'add',
                ],
            ]
        ],
        'edit' => [
            'type' => Segment::class,
            'options' => [
                'route' => '/edit[/:id]',
                'defaults' => [
                    'controller' => Controller\UsersController::class,
                    'action' => 'edit',
                ],
            ]
        ],
        'delete' => [
            'type' => Segment::class,
            'options' => [
                'route' => '/delete[/:id]',
                'defaults' => [
                    'controller' => Controller\UsersController::class,
                    'action' => 'delete',
                ],
            ]
        ],
        'paginator' => [
            'type' => Segment::class,
            'options' => [
                'route' => '/[page/:page]',
                'defaults' => [
                    'page' => 1
                ]
            ]
        ]
    ]
],
```

Just make sure you update the `<a href=""` links as it won't work with `url()` helper, so you would need to have plain links to `/users/edit/2` etc
