### ISSUE TITLE
Not in composer and impossible to download using composer: divix1988/laminas-twig-module": "^1.1"

### ISSUE THREAD

**Issue by robswebmaste** [divix1988/laminas_examples#6]
Hello everybody, Olmalek,

thanks for book. 

can not download using composer1 to 2: divix1988/laminas-twig-module": "^1.1" 
(this problem are in many Chapiters of book but form me is important in Chapitre 14 Chapitre 15 Chapitre 16)

1) Many bug with library are often do beacause i used Composer version 2 but i rollback to Composer 1 but big problems

Solution: i have tried many versions of composer (version 1.0 to version 2 ...) with command in CMD :
CMD ==> composer self-update -- 1.0    
CMD ==> composer self-update -- 1.10.19   (i test many version 1 of Composer until version 2 and last) 

but your divix1988/laminas-twig-module is not in Composer and can you add this library to Composer?

For each version i launch in (version 1 to 2...):
 CMD ==> composer upgrade (to download library in composer.json in the root of website)
 CMD ==> composer info or composer show (but composer didn't find the  library divix1988/laminas-twig-module)

2) Which version of Composer dio you use for the book?

Thanks

**Comment by divix1988** [comment]
@robswebmaste The Twig implementation is available under: https://github.com/divix1988/laminas-twig-module however it is still unfinished and has some major issues. Hence it's has not been mentioned anywhere in the book.

**Comment by divix1988** [comment]
There is some french module on github on: https://github.com/celtic34fr/laminas-got-twig I haven't tried it, but it might work for you.
