### ISSUE TITLE
problem: "zf-commons/zfc-admin": "dev-I-laminas-migration"

### ISSUE THREAD

**Issue by robswebmaste** [divix1988/laminas_examples#7]
Hello everybody; Olmalek,

problem: "zf-commons/zfc-admin": "dev-I-laminas-migration"

with version Composer 2

Solution: never use Version 2 Composer but maximum version Composer 1.10.19

to change version of Composer for example to version Composer 1.10.19 
CMD ==> composer self-update -- 1.10.19

**Comment by divix1988** [comment]
I would recommend using Composer in v1.* as v2 is not yet supported.
