### ISSUE TITLE
Button class is not supported

### ISSUE THREAD

**Issue by tyrsson** [divix1988/laminas_examples#8]
Line 71 of BootstrapFormRow:
`if ($element instanceof Submit)`
The following fixes the issue for me:
`if ($element instanceof Submit || $element instanceof Button)`
The button class is listed in the use statements which makes me think it might have just been an oversight :)

**Comment by divix1988** [comment]
Thanks for raising. Fixed in: [76bf35c](https://github.com/divix1988/laminas_examples/commit/76bf35cbb82cf37160412f5a37d0edceff7e7071)

**Comment by tyrsson** [comment]
You're welcome and thank you for all the work you put into this book. Was a lifesaver for me.
