### ISSUE TITLE
Use of form-check-input 

### ISSUE THREAD

**Issue by tyrsson** [divix1988/laminas_examples#9]
Class BootstrapFormRow line: 74
`$classString = 'form-check-input';`
Causes the checkbox to overlap the label making it unreadable. The following change fixes it for me in Firexfox Developer Edition and the most recent Google Chrome. Both on windows 10
`$classString = 'form-check';`

**Comment by divix1988** [comment]
Which version of Bootstrap are you using?

**Comment by tyrsson** [comment]
Bootstrap v4.4.1

**Comment by tyrsson** [comment]
Not sure if this will help but I figure the more info  you have the easier it is to track down. I am using firephp along with Laminas\Log for debugging and when the form loads I am getting an undefined index reported on this line:
File: BootstrapFormRow.php
Line: 139
`$classMapping[$type],`
It appears that this is for special handling of the multi_checkbox and radios which it appears you are setting the form-check mb-2 class but I have not debug much deeper than that. Just thought I would reference this in case it helps, since its your code I figured maybe it would help. I'm guessing that its due to my use of the checkbox element due to the fact that I am using two checkboxs in this particular fieldset. Of course I receive that undefined index notice twice. Once for each element.

**Comment by divix1988** [comment]
I've checked the code and it looks like it working on plain version.

Make sure you have the following css styles:
```
form#user label {
    display: block;
}
```
